import time, datetime

FPS = 800
WINDOWWIDTH = 360 # 500
WINDOWHEIGHT = 420 # 800
FIELDWIDTH = 360 # 650
FIELDHEIGHT = 420 # 650
SCREENWIDTH = 360 # 650
SCREENHEIGHT = 420 # 650
ballReleased = False
myList = []
dateString = '%d.%m.%Y %H:%M:%S'
qValue = float(0)
stateTime = time.strftime(dateString)
frame = int(0)
gameRun = int(0)
framesPerLife = int(0)
trainingRun = int(0)
totalScore = int(0)
print (datetime.datetime.now().strftime(dateString))
stepTime = float(0)
aliveGameTime = time.time()
lastSave = time.strftime("%d.%m.%Y %H:%M:%S")
model_path = ('R:\\temp\\')
states_path = ('R:\\temp\\')
repmem_path = str('B:\\breakout training saves\\') # str('C:\\Users\\me\\Documents\\CNN_Snake_SelfLearning\\CNN_Snake_SelfLearning\\breakout01\\')
#mainPath = 'C:\\Users\\me\\Documents\\LiCliPseWorkspace\\CNN_Snake_SelfLearning\\'
lastRun = 0
qLive = []
fplLive = []
scoreLive = []
epsilonLive = []
lastRun = 0
diagON = int(0)
discft = int(0)
reward = float(-0.1)
ballAlive_frames = int(0)
rundenZeit = float(0)
rundenFZeit = float(0)
thisRundenZeit = ""
done = False
saveRepmemAndExit = False
rundeDone = False
action = ''
